# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'day07' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'RecastAI'
pod 'ForecastIO'
pod 'Alamofire', '~> 4.8.0'

end
